name: Analyze host and account_indicators
id: a194130b-f5a8-4bfe-b09f-35f58f4397d5
tags:
  - picerl
  nist:
    - RS.RP
description: 1. Review Related Event information by host and account. There may be additional related events that were not forwarded yet to allow for additional investigative context
3. Validate account and endpoint information by collecting and reviewing information contained within indentity systems and asset databases.
4. Review the account types and Primary Group ID for the overall understanding of the accounts. For more information review `understanding account types` - https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/useraccountcontrol-manipulate-account-properties and `Primary Group Ids` - https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/security-identifiers-in-windows
5. Understand the different types accounts in your environment and privilege level. This initial assessment is determining if this is a `local`, 'domain', 'adminstrative' or 'VIP' account and determine if credential misuse has occurred.
6. Understand the asset that is the subject of the event.  It's is a critical system, 'server', 'workstation', 'laptop', 'mobile', or 'cloud' device.
automation:
  role:
  sla_type: minutes
  sla:
  is_note_required: false
  actions:
    - run query
    - get user attributes
    - get system attributes
  playbooks:
    - scm:
      playook:
references:
  - Understanding primary group ids
  - "https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/security-identifiers-in-windows"
  - Understanding account types
  - "https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/useraccountcontrol-manipulate-account-properties"
how_to_implement:
date: '2021-03-06'
version: 2
author: Rob Gresham, Splunk
