name: Identify vunlerabilities
id: f28177ae-78de-43c9-8692-e972e8a0aa62
tags:
  analytics_story:
    - Response Plan
  nist:
    - RS.RP
description: |
  Scan host(s) for vulnerabilities. Reverse engineer malware thru static and dynamic means to determine any zero day vulnerabilities.
  1. Scan host(s) with infection and determine any vulnerabilities that can remediate infection. (e.g. finding a SMB MS17-010 - Windows SMB Remote Code Execution Vulnerability)
  2. Identify any common vulnerabilities among the hosts infected
  3. Reverse engineer malware for any zero day vulnerabilities.
automation:
  role:
  sla_type: minutes
  sla:
  is_note_required: false
  actions:
  playbooks:
    - scm:
      playook:
references:
  - 3.3.3 Identifying the Attacking Hosts - https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-61r2.pdf
  - NIST SP 800-86, Guide to Integrating Forensic Techniques into Incident Response, for additional information on preserving evidence
how_to_implement:
date: '2021-03-06'
version: 2
author: Rob Gresham, Splunk
