name: Implement additional monitoring
id: edb7867c-2e81-4356-a422-92781f4fa34c
tags:
  - picerl
  nist:
    - RS.RP
description: |
  Implement additional monitoring that reviews not only host/network containment or eradication success. Monitor network blocks for additional hosts that might not have been identified. Reassess containment and eradication as needed depending on any new information. If this is a mass infection, it's advised that a 24 hour no change process be implemented.
  1. Create additional monitoring for network and host detection for abnormal activity to ensure containment is effective.
  2. Re-investigate new hosts found but not on the containment list
  Are the affected system numbers going stopping (containment) or down now (eradication)?  Sometimes containment and eradication techniques are accomplished in the same task. These two processes should still be determined, as new infections are getting removed eventually. The malware persistence is still available and could change the payload and then you would have new infections.
automation:
  role:
  sla_type: minutes
  sla:
  is_note_required: false
  actions:
  playbooks:
    - scm:
      playook:
references:
  - 3.2.4 Incident Analysis - https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-61r2.pdf
requirements:
how_to_implement:
date: '2021-03-06'
version: 2
author: Rob Gresham, Splunk
